name: Latest blog post workflow
on: 
    schedule:
        - cron: '50 8,20 * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "10"
                feed_list: "https://www.funkysi1701.com/index.xml"
